// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGhiCqwQWxOU2GHjpOaQN8prUldkKflYg',
    appId: '1:312935083226:web:b4147722e48b9eb15f09e3',
    messagingSenderId: '312935083226',
    projectId: 'note-taking-application-bc382',
    authDomain: 'note-taking-application-bc382.firebaseapp.com',
    storageBucket: 'note-taking-application-bc382.firebasestorage.app',
    measurementId: 'G-96ZBKSJSFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTMsePbgQ_HbYYVx0FE0w6FOxpTXixHX4',
    appId: '1:312935083226:android:bf04f56316399f4b5f09e3',
    messagingSenderId: '312935083226',
    projectId: 'note-taking-application-bc382',
    storageBucket: 'note-taking-application-bc382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChL8vRyK6BdZ13yEcZlMqpJg1BE_3D_Ug',
    appId: '1:312935083226:ios:f27387e01f9d8b0e5f09e3',
    messagingSenderId: '312935083226',
    projectId: 'note-taking-application-bc382',
    storageBucket: 'note-taking-application-bc382.firebasestorage.app',
    androidClientId: '312935083226-uukrrftsmuul9mcvsnr8eqcjdst9bbrv.apps.googleusercontent.com',
    iosClientId: '312935083226-8n4a6ltum2nrm0rkepng0hdflt4qhi3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteTakingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChL8vRyK6BdZ13yEcZlMqpJg1BE_3D_Ug',
    appId: '1:312935083226:ios:f27387e01f9d8b0e5f09e3',
    messagingSenderId: '312935083226',
    projectId: 'note-taking-application-bc382',
    storageBucket: 'note-taking-application-bc382.firebasestorage.app',
    androidClientId: '312935083226-uukrrftsmuul9mcvsnr8eqcjdst9bbrv.apps.googleusercontent.com',
    iosClientId: '312935083226-8n4a6ltum2nrm0rkepng0hdflt4qhi3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteTakingApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGhiCqwQWxOU2GHjpOaQN8prUldkKflYg',
    appId: '1:312935083226:web:f200fbc593b104b45f09e3',
    messagingSenderId: '312935083226',
    projectId: 'note-taking-application-bc382',
    authDomain: 'note-taking-application-bc382.firebaseapp.com',
    storageBucket: 'note-taking-application-bc382.firebasestorage.app',
    measurementId: 'G-TPFZJXDS82',
  );

}